# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Install vim, setup environment
      run: |
        sudo apt install -y vim
        vim --version
        echo "filetype plugin on" > $HOME/.vimrc
        mkdir -pv $HOME/.vim/pack $HOME/.vim/colors
    - name: Install vim-devel
      uses: actions/checkout@v4
      with:
        repository: lifepillar/vim-devel
        path: vim-devel
    - name: Fix vim-devel... gh does not like overriding the string() fcn in its vim installation
      run: |
        find vim-devel -name "*.vim" | xargs sed -i "s/def string/def BadString/"
        mv vim-devel $HOME/.vim/pack/devel
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - name: Clean install Node dependencies
      run: npm ci
    - name: Build all colors (including the base limbus colorscheme)
      run: |
        ./build_install.sh --name limbus
    - name: Zip results
      run: cd $HOME/.vim && zip -r colors colors
    - name: Move zipped results
      run: mv $HOME/.vim/colors.zip latest_colors.zip
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.11.5
      with:
        file: latest_colors.zip
        tag: testing
        overwrite: true
